/**
 * One school's real 2026-27 calendar, generated from its published PDF.
 *
 * A TEST FIXTURE. NOT FOR THE APP.
 *
 * It lives under src/test so that shipping it requires a shipping file to
 * import across that boundary, which is obvious in review and is checked by
 * noRealCalendar.test.ts. It used to sit in src/data and was imported by the
 * preview dataset and by the import screen, so one school's actual calendar was
 * in the production bundle twice and the preview banner announced it.
 *
 * The app uses `sampleSchoolYear` -- an invented year of the same shape and
 * span. This stays because the import and duplicate-review work needs a real
 * document to be honest about: the repeated titles, the one break filed as two
 * entries, the corrupt punctuation. Those are properties of real school
 * calendars, which is the whole reason the software has to survive them.
 *
 * Generated by scripts/build-seed.py -- do not edit by hand.
 *
 * Every entry is all-day. The source contains exactly one genuinely timed
 * event (Curriculum Night); its time stays in the description rather than
 * becoming a start time, because 16 of the 17 clock times in the document
 * describe a schedule change ("until 10 a.m.") rather than an event start.
 */
import type { PlainDate } from '@/lib/events'
import type { SeedEvent } from '@/data/seedEvent'

export type { SeedEvent }

export const SCHOOL_YEAR_2026_27 = {
  label: '2026\u201327',
  startsOn: '2026-09-01' as PlainDate,
  endsOn: '2027-06-30' as PlainDate,
}

export const schoolEvents2026_27: SeedEvent[] = [
  { title: 'New Student Orientation Morning', description: 'Special schedule — no students in school in the afternoon', startDate: '2026-09-03', endDate: '2026-09-03', category: 'school' },
  { title: 'First Day of School', description: null, startDate: '2026-09-08', endDate: '2026-09-08', category: 'academic' },
  { title: 'Safe Schools Assembly', description: 'split assembly day schedule', startDate: '2026-09-10', endDate: '2026-09-10', category: 'school' },
  { title: 'Curriculum Night', description: '5:30 - 8:30 p.m.', startDate: '2026-09-22', endDate: '2026-09-22', category: 'family' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-09-23', endDate: '2026-09-23', category: 'school' },
  { title: 'National Day for Truth and Reconciliation', description: 'Regular School Hours with a Special Schedule', startDate: '2026-09-30', endDate: '2026-09-30', category: 'school' },
  { title: 'House Track', description: 'Regular School Hours with a Special Schedule', startDate: '2026-10-01', endDate: '2026-10-01', category: 'school' },
  { title: 'PD Day', description: 'no students in school', startDate: '2026-10-09', endDate: '2026-10-09', category: 'pa-day' },
  { title: 'Holiday Monday', description: 'Thanksgiving', startDate: '2026-10-12', endDate: '2026-10-12', category: 'holiday' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-10-14', endDate: '2026-10-14', category: 'school' },
  { title: 'Designated School Break after Open House', description: 'no students in school', startDate: '2026-10-19', endDate: '2026-10-19', category: 'holiday' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-10-21', endDate: '2026-10-21', category: 'school' },
  { title: 'Parent Teacher Interviews', description: 'morning classes Nov 5 online, no students in school Nov 5 (afternoon) and all day Nov 6 & 9', startDate: '2026-11-05', endDate: '2026-11-09', category: 'family' },
  { title: '4-day Long Weekend', description: 'designated school break', startDate: '2026-11-13', endDate: '2026-11-16', category: 'holiday' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-11-18', endDate: '2026-11-18', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-11-25', endDate: '2026-11-25', category: 'school' },
  { title: 'PA Day', description: null, startDate: '2026-12-01', endDate: '2026-12-01', category: 'pa-day' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-12-02', endDate: '2026-12-02', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2026-12-16', endDate: '2026-12-16', category: 'school' },
  { title: 'Holiday Breakfast and early dismissal', description: 'Shortened Day with a Special schedule', startDate: '2026-12-18', endDate: '2026-12-18', category: 'holiday' },
  { title: 'Winter Break', description: null, startDate: '2026-12-21', endDate: '2026-12-31', category: 'holiday' },
  { title: 'Winter Break', description: null, startDate: '2027-01-01', endDate: '2027-01-03', category: 'holiday' },
  { title: 'PD Day', description: 'no students in school', startDate: '2027-01-04', endDate: '2027-01-04', category: 'pa-day' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-01-20', endDate: '2027-01-20', category: 'school' },
  { title: 'Parent Teacher Interviews', description: 'no students in school', startDate: '2027-02-05', endDate: '2027-02-08', category: 'family' },
  { title: '4-day Long Weekend', description: null, startDate: '2027-02-12', endDate: '2027-02-15', category: 'holiday' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-03-03', endDate: '2027-03-03', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-03-10', endDate: '2027-03-10', category: 'school' },
  { title: 'March Break', description: null, startDate: '2027-03-15', endDate: '2027-03-25', category: 'holiday' },
  { title: '4–Day Long Weekend weekend', description: 'Easter', startDate: '2027-03-26', endDate: '2027-03-29', category: 'holiday' },
  { title: 'PA Day and OSSLT', description: 'only M4 students in school for the OSSLT', startDate: '2027-04-06', endDate: '2027-04-06', category: 'pa-day' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-04-07', endDate: '2027-04-07', category: 'school' },
  { title: 'Day of Pink', description: 'Regular School Hours with a Special Schedule', startDate: '2027-04-14', endDate: '2027-04-14', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-04-21', endDate: '2027-04-21', category: 'school' },
  { title: 'PD Day and Student Study day', description: 'no students in school', startDate: '2027-04-30', endDate: '2027-04-30', category: 'pa-day' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-05-05', endDate: '2027-05-05', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-05-12', endDate: '2027-05-12', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-05-19', endDate: '2027-05-19', category: 'school' },
  { title: 'Holiday Monday', description: 'Victoria Day', startDate: '2027-05-24', endDate: '2027-05-24', category: 'holiday' },
  { title: 'House Island Day', description: null, startDate: '2027-05-26', endDate: '2027-05-26', category: 'school' },
  { title: 'Late Start', description: 'no students in school until 10 a.m.', startDate: '2027-06-02', endDate: '2027-06-02', category: 'school' },
  { title: 'Exam Week', description: 'mandatory attendance', startDate: '2027-06-04', endDate: '2027-06-21', category: 'exam' },
  { title: 'PA Day', description: 'no students in School', startDate: '2027-06-22', endDate: '2027-06-22', category: 'pa-day' },
  { title: 'Last Day of School for Students: Exam Review and Final Assembly', description: null, startDate: '2027-06-23', endDate: '2027-06-23', category: 'academic' },
  { title: 'S6 Graduation Day', description: null, startDate: '2027-06-24', endDate: '2027-06-24', category: 'academic' },
  { title: 'PD Day', description: 'no students in school', startDate: '2027-06-25', endDate: '2027-06-25', category: 'pa-day' },
  { title: 'PD Day', description: 'no students in school', startDate: '2027-06-28', endDate: '2027-06-28', category: 'pa-day' },
  { title: 'PD Day', description: 'no students in school', startDate: '2027-06-29', endDate: '2027-06-29', category: 'pa-day' },
  { title: 'PD Day', description: 'no students in school', startDate: '2027-06-30', endDate: '2027-06-30', category: 'pa-day' },
]
