/**
 * Light and grain behind the whole page.
 *
 * The page was flat: every surface the same value, every section boundary a
 * one-pixel rule. That reads as competent and slightly airless, and it is the
 * difference between a site that looks built and one that looks designed.
 *
 * Two layers, both fixed and both inert. A pair of very soft radial washes give
 * the ground somewhere to be lighter, so the cards have something to sit on
 * rather than float against nothing. Over them, a grain generated by SVG
 * turbulence at three per cent, which stops large flat areas from banding on
 * cheap panels and gives the whole thing a surface.
 *
 * Everything here is in theme tokens, so the vivid theme's purple washes rather
 * than the navy, and the dark theme's washes are lighter rather than darker --
 * dark mode gets depth from lightness, not from shadow.
 *
 * `fixed` rather than absolute: it must not lengthen a page that is already
 * fourteen thousand pixels tall, and it must not scroll, because a texture that
 * moves with the content is a texture you notice.
 */
export function Atmosphere() {
  return (
    <div aria-hidden className="pointer-events-none fixed inset-0 z-0 overflow-hidden">
      <div
        className="absolute -left-[15%] -top-[10%] h-[70vh] w-[60vw] rounded-full opacity-[0.5] blur-[110px]"
        style={{ background: 'radial-gradient(closest-side, var(--brand-subtle), transparent)' }}
      />
      <div
        className="absolute -right-[10%] top-[45%] h-[60vh] w-[50vw] rounded-full opacity-[0.4] blur-[120px]"
        style={{ background: 'radial-gradient(closest-side, var(--surface-2), transparent)' }}
      />
      <div
        className="absolute inset-0 opacity-[0.03] mix-blend-multiply dark:mix-blend-screen"
        style={{
          // Turbulence rather than a bitmap: no request, no cache entry, and it
          // scales to any display density without a second asset.
          backgroundImage:
            "url(\"data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='140' height='140'%3E%3Cfilter id='n'%3E%3CfeTurbulence type='fractalNoise' baseFrequency='0.9' numOctaves='3'/%3E%3C/filter%3E%3Crect width='140' height='140' filter='url(%23n)'/%3E%3C/svg%3E\")",
        }}
      />
    </div>
  )
}
