import { useLayoutEffect, useRef, useState } from 'react'
import { motion, useTransform } from 'motion/react'
import type { MotionValue } from 'motion/react'
import { PushThrough } from './Chapter'
import { useScrollScene, held, paced } from './scrollScene'
import { CountUp } from './CountUp'
import { projectStats } from '@/data/stats'

/**
 * Who made this, as a panel that opens.
 *
 * It was a separate page, which meant the one thing on the site that is about a
 * person sat behind a link most readers never followed. Here it is the last
 * thing on the page, in the position where somebody who has read all of it is
 * the one still asking.
 *
 * The mechanism is deliberately unlike anything above it. Five sections already
 * fade, converge, fly, stack and resolve; a sixth doing any of those would read
 * as the page running out of ideas. This one hinges open from its bottom edge
 * as you arrive at it -- a lid lifting -- which is a rotation on the compositor
 * and costs nothing.
 */

/**
 * The figures, read from the repository rather than typed here.
 *
 * This was a hardcoded array and every number in it had drifted: 27 tables
 * against 33, 54 policies against 72, 117 tests against 318. The page's own
 * argument is that its contents are checkable, and the one panel claiming how
 * much work is behind it was the one panel nobody was checking.
 *
 * `src/data/projectStats.ts` is generated by `npm run stats` and verified after
 * every `npm test`, so these cannot go stale quietly again.
 *
 * Three of them are set large and three are a sentence underneath, which is a
 * decision about height and not only about emphasis: this panel is pinned, so
 * it has exactly one window to fit in and nothing below the fold can be
 * scrolled to. Six figures at display size took it 223px past the bottom of a
 * 375x667 window -- and the disclaimer, which is the one line on this page that
 * has to be readable, was the part that fell off. Migrations, tables and the
 * SQL assertions read perfectly well in a line of prose; the count of tests
 * does not, because it is the number somebody is actually weighing.
 */
const NUMBERS = [
  { value: projectStats.tests, label: 'tests' },
  { value: projectStats.policies, label: 'security policies' },
  {
    value: projectStats.appLines + projectStats.testLines,
    label: 'lines of TypeScript',
  },
]

/**
 * The frame's own padding: pt-16 above the panel, pb-8 below it.
 *
 * Named rather than measured because it is the thing the panel has to fit
 * inside, and a measurement of the frame would already include the panel that
 * is overflowing it.
 */
const FRAME_PADDING = 64 + 32

export function FounderScene() {
  const { ref, reduce, progress, height } = useScrollScene(paced(2))
  const cardRef = useRef<HTMLDivElement>(null)

  /**
   * The hinge is pinned, and a pinned frame is one window tall with
   * `overflow-hidden`: whatever does not fit is not below the fold, it is gone.
   * On main this had already eaten the bottom 84px of the disclaimer at
   * 375x667 and 22px at 414x736 -- the one paragraph on this page that has to
   * be readable, cropped on the two smallest screens, on a section nobody had
   * measured because nothing about it looks like an overflow.
   *
   * So the panel is measured against the window it would be pinned in, and the
   * scene only pins where the whole thing fits. Where it does not, the same
   * card scrolls past like any other section. That is a real alternative rather
   * than a degraded one: the content is identical and all of it is readable.
   *
   * Measured rather than guessed at with a breakpoint, because the panel's
   * height is a function of how its text wraps, and the window heights that
   * fail are not the narrow ones -- 1280x700 is a laptop.
   *
   * Read once, like every other mechanism switch on this page. A window resized
   * across the threshold mid-scroll would otherwise unpin the section under the
   * reader, which is worse than either state.
   */
  const [pinned, setPinned] = useState(false)
  useLayoutEffect(() => {
    if (reduce || pinned) return
    const el = cardRef.current
    if (!el) return
    setPinned(el.offsetHeight + FRAME_PADDING <= window.innerHeight)
  }, [reduce, pinned])

  if (reduce) {
    return (
      <section id="founder" className="border-t border-border bg-bg px-5 py-20 sm:px-8">
        <div className="mx-auto max-w-[1000px]">
          <Panel />
        </div>
      </section>
    )
  }

  if (!pinned) {
    return (
      <section id="founder" className="border-t border-border bg-bg px-5 py-20 sm:px-8">
        <div ref={cardRef} className={CARD}>
          <Panel />
        </div>
      </section>
    )
  }

  return (
    <section id="founder" ref={ref} className="relative border-t border-border bg-bg" style={{ height }}>
      <div className="sticky top-0 flex h-svh items-center overflow-hidden px-5 pb-8 pt-16 sm:px-8">
        <PushThrough progress={progress} depth={300}>
          <div className="mx-auto w-full max-w-[1000px]" style={{ perspective: 1400 }}>
            <Lid progress={progress} />
          </div>
        </PushThrough>
      </div>
    </section>
  )
}

/**
 * One class list for both states, so the measurement is of the thing that gets
 * pinned rather than of something the same shape.
 */
const CARD = 'mx-auto w-full max-w-[1000px] rounded-2xl border border-border bg-surface p-8 shadow-lg sm:p-12'

function Lid({ progress }: { progress: MotionValue<number> }) {
  // Open across the first half of the scene, so it is fully readable well
  // before the section lets go of the viewport.
  const [oR, oV] = held([0.06, 0.46], [0, 1])
  const t = useTransform(progress, oR, oV)

  // Hinged at the bottom edge: the top swings up toward the reader.
  const rotateX = useTransform(t, [0, 1], [-74, 0])
  const opacity = useTransform(t, [0, 0.28], [0, 1])
  // Content arrives after the panel is most of the way open, so it is never
  // read at an angle steep enough to distort it.
  const inner = useTransform(t, [0.55, 1], [0, 1])

  return (
    <motion.div
      style={{ rotateX, opacity, transformOrigin: 'bottom center', transformStyle: 'preserve-3d' }}
      className={CARD}
    >
      <motion.div style={{ opacity: inner }}>
        <Panel />
      </motion.div>
    </motion.div>
  )
}

/**
 * The content itself, identical whether it arrived by hinge or by scrolling.
 *
 * Deliberately short. It began as a paragraph of six lines and a row of four
 * figures, which is a lot of reading to arrive at after nine thousand pixels --
 * and the figures were doing the persuading anyway. Two sentences, then the
 * numbers, then the disclaimer that has to be here.
 *
 * All six figures are here now: three set large, and three inside the sentence
 * that was already describing what was built. Six at display size was tried and
 * measured -- at 375x667 it pushed the panel 223px past the bottom of a frame
 * that is pinned and cannot scroll, taking the disclaimer with it -- and so was
 * a separate paragraph for the other three, which cost a block of its own and
 * unpinned the hinge on a 1280x700 laptop. Numbers a reader weighs are set
 * large; numbers that are evidence read fine in a line of prose.
 */
function Panel() {
  return (
    <>
      <p className="label-caps text-accent">Created by</p>
      <h2 className="mt-4 font-display text-display font-medium leading-[1.0] tracking-[-0.02em]">
        Anshu Arunav
      </h2>
      <p className="mt-6 max-w-[46ch] text-[17px] leading-relaxed text-text sm:text-[19px]">
        A student who wanted the school year to stop living in four places at once, and
        built the thing that fixes it.
      </p>
      <p className="mt-3 max-w-[52ch] text-[14.5px] leading-relaxed text-text-muted">
        Alone, end to end — {projectStats.migrations} migrations behind{' '}
        {projectStats.tables} tables, authentication, notifications that reach a phone,
        and {projectStats.sqlAssertions} database assertions that sign in as the wrong
        person and require failure.
      </p>

      <dl className="mt-9 flex flex-wrap gap-x-12 gap-y-6 border-t border-border pt-7">
        {NUMBERS.map((n) => (
          <div key={n.label}>
            <dt className="font-display text-display-sm font-medium leading-none tracking-tight text-text">
              <CountUp to={n.value} />
            </dt>
            <dd className="mt-2 text-[12px] leading-snug text-text-subtle">{n.label}</dd>
          </div>
        ))}
      </dl>

      <p className="mt-4 text-[12px] leading-relaxed text-text-subtle">
        Counted from the repository on every test run, never typed.
      </p>

      <p className="mt-8 max-w-[60ch] border-t border-border pt-6 text-[12px] leading-relaxed text-text-subtle">
        A personal project. Not affiliated with, endorsed by, or an official product of
        any school.
      </p>
    </>
  )
}
