#!/usr/bin/env python3
"""
Generates src/data/schoolCalendar.ts from the extracted PDF data.

Run from the repo root:  python3 scripts/build-seed.py

The source titles pack an event name and a schedule note into one string, in
two different orders:

    "Safe Schools Assembly - split assembly day schedule"   name first
    "Special schedule - New Student Orientation Morning"    note first

so the split has to look at which half is the schedule note, rather than
always taking the same side.
"""
import json
import re
from collections import Counter
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs/discovery/school-dates-2026-27.json"
TARGET = ROOT / "src/data/schoolCalendar.ts"

# Phrases that mark a half as a schedule note rather than the event's name.
SCHEDULE_NOTE = re.compile(
    r"special schedule|regular school hours|shortened day|split assembly|"
    r"day schedule|special\s+schedule", re.IGNORECASE)


def categorise(title: str) -> str:
    t = title.lower()
    # Order matters: "Last Day of School ... Exam Review" is the last day, not
    # an exam, so the day-of-term rules are checked before the exam rule.
    if "first day" in t or "last day" in t:              return "academic"
    if "exam" in t:                                      return "exam"
    if "pd day" in t or "pa day" in t:                   return "pa-day"
    if "holiday monday" in t:                            return "holiday"
    if "break" in t or "long weekend" in t:              return "holiday"
    if "parent teacher" in t or "curriculum night" in t: return "family"
    if "graduation" in t:                                return "academic"
    return "school"


def split_title(raw: str) -> tuple[str, str | None]:
    """Returns (title, description). Parenthetical detail becomes description."""
    detail = None
    body = raw.strip()

    m = re.match(r"^(.*?)\s*\((.*)\)\s*$", body)
    if m and len(m.group(1).strip()) > 3:
        body, detail = m.group(1).strip(), m.group(2).strip()

    if " - " in body:
        head, tail = (p.strip() for p in body.split(" - ", 1))
        # Whichever half is the schedule note becomes the description; the
        # other half is the event's actual name.
        if SCHEDULE_NOTE.search(head) and not SCHEDULE_NOTE.search(tail):
            body, note = tail, head
        elif SCHEDULE_NOTE.search(tail) and not SCHEDULE_NOTE.search(head):
            body, note = head, tail
        else:
            body, note = head, tail
        detail = f"{note} — {detail}" if detail else note

    return body, detail


def ts(value: str | None) -> str:
    if value is None:
        return "null"
    escaped = value.replace("\\", "\\\\").replace("'", "\\'")
    return f"'{escaped}'"


def main() -> None:
    events = json.loads(SOURCE.read_text())
    rows = []
    for e in events:
        title, description = split_title(e["title"])
        rows.append({
            "title": title,
            "description": description,
            "startDate": e["start_date"],
            "endDate": e["end_date"],
            "category": categorise(e["title"]),
        })

    body = "\n".join(
        "  { title: %s, description: %s, startDate: %s, endDate: %s, category: %s },"
        % (ts(r["title"]), ts(r["description"]), ts(r["startDate"]),
           ts(r["endDate"]), ts(r["category"]))
        for r in rows
    )

    TARGET.write_text(f'''/**
 * The 2026-27 school calendar, generated from the source PDF.
 *
 * Generated by scripts/build-seed.py -- do not edit by hand.
 *
 * Every entry is all-day. The source contains exactly one genuinely timed
 * event (Curriculum Night); its time stays in the description rather than
 * becoming a start time, because 16 of the 17 clock times in the document
 * describe a schedule change ("until 10 a.m.") rather than an event start.
 *
 * Used two ways:
 *   - the preview dataset shown before Supabase is connected
 *   - the fixture for the Phase 3 import and duplicate-review work
 */
import type {{ PlainDate }} from '@/lib/events'

export type SeedEvent = {{
  title: string
  description: string | null
  startDate: PlainDate
  endDate: PlainDate
  category: string
}}

export const SCHOOL_YEAR_2026_27 = {{
  label: '2026\\u201327',
  startsOn: '2026-09-01' as PlainDate,
  endsOn: '2027-06-30' as PlainDate,
}}

export const schoolEvents2026_27: SeedEvent[] = [
{body}
]
''')
    print(f"generated {len(rows)} events -> {TARGET.relative_to(ROOT)}")
    print("categories:", Counter(r["category"] for r in rows).most_common())


if __name__ == "__main__":
    main()
