// Generated by scripts/write-project-stats.mjs -- do not edit by hand.
// Run `npm run stats` after adding or removing tests.
//
// This is the one figure on the founder panel that cannot be counted from the
// source: one `it.each` over five files is one match and five tests, so only
// the runner knows. `npm test` checks this file on the way out.

/** Tests vitest ran, as vitest counted them. */
export const testCount = 334
